### ISSUE TITLE
Demo: Snow Field Effect [Points/Sprites]

### ISSUE THREAD

**Issue by DennisSmolek** [hmans/three-vfx#12]
Replicating the Vanilla Snow Ponts/Sprites Demo seen here:
https://threejs.org/examples/?q=sprite#webgl_points_sprites

Also closes #5 
<img width="700" alt="Screen Shot 2022-06-07 at 10 45 58" src="https://user-images.githubusercontent.com/1397052/172426543-5c42e63d-fb18-47d8-8243-edb042be8ca6.png">

**Comment by hmans** [comment]
I now have a snow demo here: https://three-vfx-examples.vercel.app/snow

Sprites are currently implemented using billboarded meshes.
